AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4
  Include:
    - '**/*.frb'

Style/Documentation:
  Enabled: false

# These names are fixed
Naming/FileName:
  Exclude: ['Gemfile', 'Rakefile']

# Yes, the main script is a bit weird
Metrics/AbcSize:
  Exclude: ['bin/frebby']
Metrics/CyclomaticComplexity:
  Exclude: ['bin/frebby']
Metrics/MethodLength:
  Exclude: ['bin/frebby']
Metrics/PerceivedComplexity:
  Exclude: ['bin/frebby']
Style/MethodMissing:
  Exclude: ['bin/frebby']

# These are just examples, so it's fine
Style/FrozenStringLiteralComment:
  Exclude: ['examples/**/*.frb']
Style/BlockDelimiters:
  Exclude: ['examples/**/*.frb']
Style/BracesAroundHashParameters:
  Exclude: ['examples/**/*.frb']
Metrics/BlockLength:
  Exclude: ['examples/**/*.frb']
Lint/AmbiguousBlockAssociation:
  Exclude: ['examples/**/*.frb']
